version: '3'

services:
  devpass-api:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    container_name: organizer-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data